spring.application.name=primeiros-passos
nome=Marcus Silva
email=marcus@example.com
telefones=11999999999,21988888888

remetente.nome=Joao Souza
remetente.email=joao@example.com
remetente.telefones=12955559999,22977788888